# Generated by Django 5.2.15 on 2026-06-09 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='当前库存数量')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='单位')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.material', verbose_name='物料')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='产品')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplier', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存批次',
                'verbose_name_plural': '库存批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '库存调整')], max_length=20, verbose_name='流水类型')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='入库/出库填写正数；库存调整可以填写正数或负数。', max_digits=14, verbose_name='数量')),
                ('before_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='变动前库存')),
                ('after_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='变动后库存')),
                ('document_no', models.CharField(blank=True, max_length=100, verbose_name='来源单号')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='原因')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_applied', models.BooleanField(default=False, verbose_name='是否已应用')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='应用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch', verbose_name='库存批次')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('material', 'warehouse', 'batch_no'), name='unique_material_batch_in_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'batch_no'), name='unique_product_batch_in_warehouse'),
        ),
    ]
