# Generated by Django 5.2.15 on 2026-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='这一批库存的实际成本单价。后续采购入库时会自动带入采购单价。', max_digits=12, verbose_name='本批次成本单价'),
        ),
    ]
