# Generated by Django 5.2.15 on 2026-06-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='仓库编号')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('hardness', models.CharField(blank=True, max_length=50, verbose_name='硬度')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='单位')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物料编号')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_type', models.CharField(choices=[('rubber', '橡胶原料'), ('filler', '填料'), ('oil', '油料'), ('agent', '助剂'), ('package', '包装材料'), ('other', '其他')], max_length=30, verbose_name='物料类型')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='单位')),
                ('safety_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='安全库存')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.supplier', verbose_name='默认供应商')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
    ]
