# Generated by Django 5.2.15 on 2026-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元'), ('JPY', '日元')], default='CNY', max_length=10, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='material',
            name='reference_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='仅作为参考价格。真实成本以后以采购单价和库存批次成本为准。', max_digits=12, verbose_name='参考采购单价'),
        ),
    ]
